export const productos = [
	{ nombre: "Manzana", precio: 0.5 },
	{ nombre: "Banana", precio: 0.3 },
	{ nombre: "Cereza", precio: 2 },
	{ nombre: "Durazno", precio: 1.5 },
	{ nombre: "Espinaca", precio: 3 },
	{ nombre: "Fresa", precio: 2.5 },
	{ nombre: "Granada", precio: 2.8 },
	{ nombre: "Higo", precio: 3 },
	{ nombre: "Iced Tea", precio: 1.2 },
	{ nombre: "Jugo de naranja", precio: 2 },
	{ nombre: "Kiwi", precio: 1.7 },
	{ nombre: "Limón", precio: 0.5 },
	{ nombre: "Mango", precio: 2 },
	{ nombre: "Nuez", precio: 5 },
	{ nombre: "Oreo", precio: 2.5 },
	{ nombre: "Pan integral", precio: 2 },
	{ nombre: "Queso cheddar", precio: 4 },
	{ nombre: "Rábanos", precio: 1.3 },
	{ nombre: "Salchicha", precio: 3.5 },
	{ nombre: "Té verde", precio: 2.5 },
	{ nombre: "Uvas", precio: 2.5 },
	{ nombre: "Vino tinto", precio: 10 },
	{ nombre: "Waffles", precio: 3 },
	{ nombre: "Xoconostle", precio: 2 },
	{ nombre: "Yogur", precio: 1.5 },
	{ nombre: "Zanahoria", precio: 1.2 },
	{ nombre: "Arroz", precio: 1 },
	{ nombre: "Bistec", precio: 5 },
	{ nombre: "Camarones", precio: 10 },
	{ nombre: "Dátiles", precio: 3 },
	{ nombre: "Ensalada", precio: 4 },
	{ nombre: "Flan", precio: 2 },
	{ nombre: "Galletas", precio: 2 },
	{ nombre: "Helado", precio: 3 },
	{ nombre: "Jícama", precio: 1.5 },
	{ nombre: "Kale", precio: 3 },
	{ nombre: "Lentejas", precio: 1.5 },
	{ nombre: "Miel", precio: 5 },
	{ nombre: "Nachos", precio: 3 },
	{ nombre: "Obleas", precio: 1.2 },
	{ nombre: "Pasta", precio: 2 },
	{ nombre: "Quinoa", precio: 4 },
	{ nombre: "Ribs", precio: 12 },
	{ nombre: "Salmón", precio: 8 },
	{ nombre: "Tacos", precio: 3 },
	{ nombre: "Udon", precio: 5 },
	{ nombre: "Vainilla", precio: 3 },
	{ nombre: "Whisky", precio: 20 },
	{ nombre: "Xocolatl (chocolate)", precio: 2 },
	{ nombre: "Yakimeshi", precio: 5 },
];
